[versions]
dokka = "2.2.0"
gradle-wrapper = "9.8.0"
jvm = "17"
kotest = "6.2.5"
kotlin = "2.4.20"
kotlinter = "5.7.0"
logback = "1.6.4"
maven-publish = "0.37.0"
versions = "0.64.0"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradle = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
ben-manes-versions = { id = "io.github.ben-manes.versions", version.ref = "versions" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
